CREATE table carro(
codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
marca VARCHAR(50) NOT NULL,
modelo VARCHAR(50) NOT NULL,
tipo VARCHAR(50) NOT NULL,
ano DATE NOT NULL,
valor DECIMAL(10, 2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;